description: >-
  TJAPlayer3 Documentation, compiled by @IepIweidieng
author:
  name: Wei-Cheng Yeh (IepIweidieng)
  url: https://github.com/IepIweidieng

permalink: pretty
plugins:
  - jekyll-relative-links
  - jemoji
  - jekyll-sitemap
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - TJAPlayer3-AioiLight-docs/README.md
  - tja.md
defaults:
  - scope:
      path: "**/*_files"
    values:
      sitemap: false
